### ISSUE TITLE
eQuest complains about redundancy in object names due to char limit

### ISSUE THREAD

**Issue by TfedUD** [ladybug-tools/dragonfly-doe2#8]
eQuest sees the following as the same and it causes issues:
```
Typical Insulated Steel Framed Exterior Wall-R19
Typical Insulated Steel Framed Exterior Floor-R27
eQuest sees:: Typical Insulated Steel Framed E
```
eQuest obj name len(limit) == 32

**Comment by mostaphaRoudsari** [comment]
Hi @TfedUD! I know some strange case should come up! This can become a challenge since we have to change the name in several places. The easiest way is probably to implement some abbreviation by removing vowels - similar to the joke that says: `you cn stl rd ths`.

Then we have to ensure that we pass all the names through this function before assigning them. I did a quick test and this seems to work:

```python
import re

def short_name(name, max_length):
    if len(name) <= max_length:
        return name
    # try to remove vowels and - and _
    shorten_name = ''.join(re.split('[aeiouy\-\_]', name))

    if len(shorten_name) <= max_length:
        return shorten_name

    # that wasn't enough - also remove white spaces
    shorten_name = ''.join(shorten_name.split())
    if len(shorten_name) > max_length:
        raise ValueError(
            f'{name} cannot be shorten to fit the eQuest limitation of 32 characters. '
            'You need to change the name manually to be shorter than 32 characters.'
        )
    return shorten_name
```

Here is a quick test with the inputs:

```python
cases = (
    'Typical Insulated Steel Framed Exterior Wall-R19' ,
    'Typical Insulated Steel Framed Exterior Floor-R27'
)

max_length = 32
for case in cases:
    print(short_name(case, max_length))
```

It should give you this which is still readable - somewhat readable! :)

```
TpclInsltdStlFrmdExtrrWllR19
TpclInsltdStlFrmdExtrrFlrR27
```

**Comment by TfedUD** [comment]
noice!

**Comment by TfedUD** [comment]
I added a... its a utils.py not a random drawer!! file with the function; and applied it to the construction class; as is the current file issue: but will implement on all ```.display_name``` callingpoints once gets this file working 4.0!

**Comment by TfedUD** [comment]
should have this closed shortly:
  Would doing a model 'pre-process' at the writer.py level be a decent option for 'having to implement this at minimal levels'?
  Step through DF_Model: short_name(disp_name for disp_name in all_objects.disp_name, 32) kinda thing?

**Comment by mostaphaRoudsari** [comment]
Hi @TfedUD, I'll see how you have done it when you send the PR but I imagine it should be done in a distributed manner so if someone only uses one of the methods it also works for them. I think it should be implemented in the model class not in the writer.

**Comment by TfedUD** [comment]
Sounds good; I'll do a PR now; theres still some tinkering needed but I think geom's going to be showing up and such without any eQuest input sans opening the *.inp tomorrowish
